
import java.time.LocalDate;
import java.time.Period;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author HP
 */
public class BiodataMahasiswa extends javax.swing.JFrame {

    /**
     * Creates new form Biodatamaha
     */
    public BiodataMahasiswa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNama = new javax.swing.JLabel();
        jLabelTL = new javax.swing.JLabel();
        JlabelAlamat = new javax.swing.JLabel();
        tfnama = new javax.swing.JTextField();
        tfalamat = new javax.swing.JTextField();
        Ctanggal = new javax.swing.JComboBox();
        Cbulan = new javax.swing.JComboBox();
        Ctahun = new javax.swing.JComboBox();
        Bproeses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TAnama = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TAtanggalLahir = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TAalamat = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        TAusia = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelNama.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabelNama.setText("NAMA");

        jLabelTL.setText("Tanggal Lahir");

        JlabelAlamat.setText("Alamat");

        Ctanggal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        Cbulan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        Cbulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbulanActionPerformed(evt);
            }
        });

        Ctahun.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006" }));

        Bproeses.setText("PROSES");
        Bproeses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BproesesActionPerformed(evt);
            }
        });

        TAnama.setColumns(20);
        TAnama.setRows(5);
        jScrollPane1.setViewportView(TAnama);

        TAtanggalLahir.setColumns(20);
        TAtanggalLahir.setRows(5);
        jScrollPane2.setViewportView(TAtanggalLahir);

        TAalamat.setColumns(20);
        TAalamat.setRows(5);
        jScrollPane3.setViewportView(TAalamat);

        TAusia.setColumns(20);
        TAusia.setRows(5);
        jScrollPane4.setViewportView(TAusia);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNama)
                    .addComponent(jLabelTL)
                    .addComponent(JlabelAlamat))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfnama)
                    .addComponent(tfalamat)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Bproeses)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Ctanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(Cbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(Ctahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 83, Short.MAX_VALUE)))
                .addGap(153, 153, 153))
            .addComponent(jScrollPane1)
            .addComponent(jScrollPane2)
            .addComponent(jScrollPane3)
            .addComponent(jScrollPane4)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNama)
                    .addComponent(tfnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTL)
                    .addComponent(Ctanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Cbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Ctahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfalamat, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JlabelAlamat))
                .addGap(33, 33, 33)
                .addComponent(Bproeses)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(72, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CbulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbulanActionPerformed

    @SuppressWarnings("empty-statement")
    private void BproesesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BproesesActionPerformed
        // TODO add your handling code here:
        
        int tanggalL =  Integer.parseInt((String) Ctanggal.getSelectedItem());
        int bulanL = Cbulan.getSelectedIndex() + 1;
        int tahunL =  Integer.parseInt((String) Ctahun.getSelectedItem());
        
        TAnama.setText("Nama        : "+tfnama.getText());
        TAtanggalLahir.setText("Tanggal Lahir: "+Ctanggal.getSelectedItem() + " " + Cbulan.getSelectedItem() + " " +Ctahun.getSelectedItem());
        TAalamat.setText("Alamat        : "+tfalamat.getText());
        
        
        LocalDate birthdate = LocalDate.of(tahunL, bulanL, tanggalL);
                LocalDate currentDate = LocalDate.now();
                Period period = Period.between(birthdate, currentDate);
                
                int Tahun = period.getYears();
                int Bulan = period.getMonths();
                int Hari = period.getDays();
                
                TAusia.setText("Usia    : " + " " + Tahun + " tahun, " + Bulan + " bulan, " + Hari + " hari");
    }//GEN-LAST:event_BproesesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BiodataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BiodataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BiodataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BiodataMahasiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BiodataMahasiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Bproeses;
    private javax.swing.JComboBox Cbulan;
    private javax.swing.JComboBox Ctahun;
    private javax.swing.JComboBox Ctanggal;
    private javax.swing.JLabel JlabelAlamat;
    private javax.swing.JTextArea TAalamat;
    private javax.swing.JTextArea TAnama;
    private javax.swing.JTextArea TAtanggalLahir;
    private javax.swing.JTextArea TAusia;
    private javax.swing.JLabel jLabelNama;
    private javax.swing.JLabel jLabelTL;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextField tfalamat;
    private javax.swing.JTextField tfnama;
    // End of variables declaration//GEN-END:variables
}
